name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*" # Triggers on version tags like v1.0.0

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Release Notes
        id: generate_notes
        uses: conventional-changelog/releaser-action@v1
        with:
          preset: "angular"

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.RELEASE_ACTION }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          commit: ${{ github.sha }}
          draft: false
          prerelease: false
          body: ${{ steps.generate_notes.outputs.notes }}
